### ISSUE TITLE
兄弟你的系统有漏洞,会造成用户数据泄漏

### ISSUE THREAD

**Issue by Binaryify** [acgzone/clicli-admin#3]

**Comment by 132yse** [comment]
所以，pr呢？

**Comment by Binaryify** [comment]
后台是go吧,不太懂go的语法
具体漏洞是提权漏洞,返回的roles 被拦截修改后,可被提权到管理员,可修改稿件啥的,另外用户列表也会被看到,总数大概是103xx

**Comment by 132yse** [comment]
用户接口当然能看到
鉴权 bug 一直存在，唉

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/57635663-2ffde700-75da-11e9-9624-17c0b7257ffc.png)
 刚刚还以为是测试环境,改了下,又改回来了

**Comment by 132yse** [comment]
嗯……是这样……很多人利用鉴权bug，篡改内容
我也很无奈，有时间再修复吧T﹏T

**Comment by Binaryify** [comment]
嗯
